name: Build Application

on:
    push:
        branches: [ main, master ]
    pull_request:
        branches: [ main, master ]

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: |
                  pnpm install
                  pnpm add -g @quasar/cli
                  pnpm add -g electron-packager
                  pnpm add -g electron-builder

            - name: Build Windows x64
              run: pnpm run build:winx64

            - name: Build Windows ia32
              run: pnpm run build:winia32

            - name: Build Mac Intel
              run: pnpm run build:intel

            - name: Build Mac ARM
              run: pnpm run build:arm

            - name: Upload Windows x64 Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: windows-x64
                  path: release/Packaged/*.exe

            - name: Upload Windows ia32 Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: windows-ia32
                  path: release/Packaged/*.exe

            - name: Upload Mac Intel Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: mac-intel
                  path: release/Packaged/*.dmg

            - name: Upload Mac ARM Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: mac-arm
                  path: release/Packaged/*.dmg
